name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ vars.DOCKER_USERNAME }}/nextjs-app:latest \
            -t ${{ vars.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }} .

      - name: Push Docker Images
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/nextjs-app:latest
          docker push ${{ vars.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
